### Filtering Data

In [3]:
import pandas as pd

In [4]:
data=pd.read_csv('modified.csv')

In [5]:
data.head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318,1
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,405,1
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1

In [6]:
new_df=data.loc[(data['Type 1']=='Grass') & (data['Type 2']=='Poison')]

In [7]:
new_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318,1
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,405,1
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,320,1
49,44,Gloom,Grass,Poison,60,65,70,85,75,40,395,1
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,490,1
75,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,300,1
76,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,390,1
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,490,1
344,315,Roselia,Grass,Poison,50,60,45,100,80,65,400,3
451,406,Budew,Grass,Poison,40,30,35,50,70,55,280,4
452,407,Roserade,Grass,Poison,60,70,65,125,105,90,515,4
651,590,Foongus,Grass,Poison,69,55,45,55,55,15,294,5
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,464,5

In [8]:
new_df.reset_index(drop=True,inplace=True)
new_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318,1
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,405,1
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1
4,43,Oddish,Grass,Poison,45,50,55,75,65,30,320,1
5,44,Gloom,Grass,Poison,60,65,70,85,75,40,395,1
6,45,Vileplume,Grass,Poison,75,80,85,110,90,50,490,1
7,69,Bellsprout,Grass,Poison,50,75,35,70,30,40,300,1
8,70,Weepinbell,Grass,Poison,65,90,50,85,45,55,390,1
9,71,Victreebel,Grass,Poison,80,105,65,100,70,70,490,1
10,315,Roselia,Grass,Poison,50,60,45,100,80,65,400,3
11,406,Budew,Grass,Poison,40,30,35,50,70,55,280,4
12,407,Roserade,Grass,Poison,60,70,65,125,105,90,515,4
13,590,Foongus,Grass,Poison,69,55,45,55,55,15,294,5
14,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,464,5

In [9]:
mega_df=data.loc[~data['Name'].str.contains('Mega')]  # ~ - it is used for 'not' operator 
mega_df.reset_index(drop=True,inplace=True)
mega_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318,1
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,405,1
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1
3,4,Charmander,Fire,NaN,39,52,43,60,50,65,309,1
4,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,405,1
...,...,...,...,...,...,...,...,...,...,...,...,...
746,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,600,6
747,719,Diancie,Rock,Fairy,50,100,150,100,150,50,600,6
748,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,600,6
749,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,680,6
750,721,Volcanion,Fire,Water,80,110,120,130,90,70,600,6

## Use Regex

In [10]:
# using regex
import re
data.loc[data['Name'].str.contains('^Bu[a-z]*y$',flags=re.I,regex=True)]  # it is find name starts with Bu and having multiple charecter and end with r

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation
457,412,Burmy,Bug,NaN,40,29,45,29,45,36,224,4
474,427,Buneary,Normal,NaN,55,66,44,44,56,85,350,4
727,659,Bunnelby,Normal,NaN,38,36,38,32,36,57,237,6

## Conditional Changes

In [11]:
data.loc[data['Type 1']=='Fire','Type 1']='Flamer'
data

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318,1
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,405,1
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1
4,4,Charmander,Flamer,NaN,39,52,43,60,50,65,309,1
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,600,6
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,700,6
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,600,6
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,680,6
799,721,Volcanion,Flamer,Water,80,110,120,130,90,70,600,6

In [12]:
data.loc[data['Type 1']=='Flamer']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation
4,4,Charmander,Flamer,NaN,39,52,43,60,50,65,309,1
5,5,Charmeleon,Flamer,NaN,58,64,58,80,65,80,405,1
6,6,Charizard,Flamer,Flying,78,84,78,109,85,100,534,1
7,6,CharizardMega Charizard X,Flamer,Dragon,78,130,111,130,85,100,634,1
8,6,CharizardMega Charizard Y,Flamer,Flying,78,104,78,159,115,100,634,1
42,37,Vulpix,Flamer,NaN,38,41,40,50,65,65,299,1
43,38,Ninetales,Flamer,NaN,73,76,75,81,100,100,505,1
63,58,Growlithe,Flamer,NaN,55,70,45,70,50,60,350,1
64,59,Arcanine,Flamer,NaN,90,110,80,100,80,95,555,1
83,77,Ponyta,Flamer,NaN,50,85,55,65,65,90,410,1
84,78,Rapidash,Flamer,NaN,65,100,70,80,80,105,500,1
135,126,Magmar,Flamer,NaN,65,95,57,100,85,93,495,1
147,136,Flareon,Flamer,NaN,65,130,60,95,110,65,525,1
158,146,Moltres,Flamer,Flying,90,100,90,125,85,90,580,1
169,155,Cyndaquil,Flamer,NaN,39,52,43,60,50,65,309,2
170,156,Quilava,Flamer,NaN,58,64,58,80,65,80,405,2
171,157,Typhlosion,Flamer,NaN,78,84,78,109,85,100,534,2
236,218,Slugma,Flamer,NaN,40,40,40,70,40,20,250,2
237,219,Magcargo,Flamer,Rock,50,50,120,80,80,30,410,2
259,240,Magby,Flamer,NaN,45,75,37,70,55,83,365,2
263,244,Entei,Flamer,NaN,115,115,85,90,75,100,580,2
270,250,Ho-oh,Flamer,Flying,106,130,90,110,154,90,680,2
276,255,Torchic,Flamer,NaN,45,60,40,70,50,45,310,3
277,256,Combusken,Flamer,Fighting,60,85,60,85,60,55,405,3
278,257,Blaziken,Flamer,Fighting,80,120,70,110,70,80,530,3
279,257,BlazikenMega Blaziken,Flamer,Fighting,80,160,80,130,80,100,630,3
352,322,Numel,Flamer,Ground,60,60,40,65,45,35,305,3
353,323,Camerupt,Flamer,Ground,70,100,70,105,75,40,460,3
354,323,CameruptMega Camerupt,Flamer,Ground,70,120,100,145,105,20,560,3
355,324,Torkoal,Flamer,NaN,70,85,140,85,70,20,470,3
435,390,Chimchar,Flamer,NaN,44,58,44,58,44,61,309,4
436,391,Monferno,Flamer,Fighting,64,78,52,78,52,81,405,4
437,392,Infernape,Flamer,Fighting,76,104,71,104,71,108,534,4
518,467,Magmortar,Flamer,NaN,75,95,67,125,95,83,540,4
542,485,Heatran,Flamer,Steel,91,90,106,130,106,77,600,4
557,498,Tepig,Flamer,NaN,65,63,45,45,45,45,308,5
558,499,Pignite,Flamer,Fighting,90,93,55,70,55,55,418,5
559,500,Emboar,Flamer,Fighting,110,123,65,100,65,65,528,5
572,513,Pansear,Flamer,NaN,50,53,48,53,48,64,316,5
573,514,Simisear,Flamer,NaN,75,98,63,98,63,101,498,5
614,554,Darumaka,Flamer,NaN,70,90,45,15,45,50,315,5
615,555,DarmanitanStandard Mode,Flamer,NaN,105,140,55,30,55,95,480,5
616,555,DarmanitanZen Mode,Flamer,Psychic,105,30,105,140,105,55,540,5
692,631,Heatmor,Flamer,NaN,85,97,66,105,66,65,484,5
721,653,Fennekin,Flamer,NaN,40,45,40,62,60,60,307,6
722,654,Braixen,Flamer,NaN,59,59,58,90,70,73,409,6
723,655,Delphox,Flamer,Psychic,75,69,72,114,100,104,534,6
730,662,Fletchinder,Flamer,Flying,62,73,55,56,52,84,382,6
731,663,Talonflame,Flamer,Flying,78,81,71,74,69,126,499,6
735,667,Litleo,Flamer,Normal,62,50,58,73,54,72,369,6
736,668,Pyroar,Flamer,Normal,86,68,72,109,66,106,507,6
799,721,Volcanion,Flamer,Water,80,110,120,130,90,70,600,6

In [13]:
data.loc[data['Type 1']=='Flamer','Type 1']='Fire'

In [14]:
data.loc[data['Type 1']=='Fire']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,309,1
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,405,1
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,534,1
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,634,1
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,634,1
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,299,1
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,505,1
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,350,1
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,555,1
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,410,1
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,500,1
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,495,1
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,525,1
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,580,1
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,309,2
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,405,2
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,534,2
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,250,2
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,410,2
259,240,Magby,Fire,NaN,45,75,37,70,55,83,365,2
263,244,Entei,Fire,NaN,115,115,85,90,75,100,580,2
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,680,2
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,310,3
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,405,3
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,530,3
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,630,3
352,322,Numel,Fire,Ground,60,60,40,65,45,35,305,3
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,460,3
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,560,3
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,470,3
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,309,4
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,405,4
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,534,4
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,540,4
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,600,4
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,308,5
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,418,5
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,528,5
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,316,5
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,498,5
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,315,5
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,480,5
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,540,5
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,484,5
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,307,6
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,409,6
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,534,6
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,382,6
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,499,6
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,369,6
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,507,6
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,600,6

## Aggregate Statistics (Group By)

In [15]:
import numpy as np
data1=pd.read_csv('modified.csv')

In [16]:
data1.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318,1
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,405,1
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,309,1

In [17]:
data1.groupby(['Type 1'])['Attack'].min()

Type 1
Bug         10
Dark        50
Dragon      50
Electric    30
Fairy       20
Fighting    35
Fire        30
Flying      30
Ghost       30
Grass       27
Ground      40
Ice         30
Normal       5
Poison      43
Psychic     20
Rock        40
Steel       24
Water       10
Name: Attack, dtype: int64

In [18]:
data1.groupby(['Type 1'])['Attack'].max()

Type 1
Bug         185
Dark        150
Dragon      180
Electric    123
Fairy       131
Fighting    145
Fire        160
Flying      115
Ghost       165
Grass       132
Ground      180
Ice         130
Normal      160
Poison      106
Psychic     190
Rock        165
Steel       150
Water       155
Name: Attack, dtype: int64

In [19]:
all_count=data1.groupby(['Type 1','Type 2']).count()

In [20]:
all_count

                  #  Name  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1 Type 2
Bug    Electric   2     2   2       2        2        2        2      2
       Fighting   2     2   2       2        2        2        2      2
       Fire       2     2   2       2        2        2        2      2
       Flying    14    14  14      14       14       14       14     14
       Ghost      1     1   1       1        1        1        1      1
...              ..   ...  ..     ...      ...      ...      ...    ...
Water  Ice        3     3   3       3        3        3        3      3
       Poison     3     3   3       3        3        3        3      3
       Psychic    5     5   5       5        5        5        5      5
       Rock       4     4   4       4        4        4        4      4
       Steel      1     1   1       1        1        1        1      1

                 Total  Generation
Type 1 Type 2
Bug    Electric      2           2
       Fighting      2           2
       Fire          2           2
       Flying       14          14
       Ghost         1           1
...                ...         ...
Water  Ice           3           3
       Poison        3           3
       Psychic       5           5
       Rock          4           4
       Steel         1           1

[136 rows x 10 columns]

                  #  Name  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1 Type 2
Bug    Electric   2     2   2       2        2        2        2      2
       Fighting   2     2   2       2        2        2        2      2
       Fire       2     2   2       2        2        2        2      2
       Flying    14    14  14      14       14       14       14     14
       Ghost      1     1   1       1        1        1        1      1
...              ..   ...  ..     ...      ...      ...      ...    ...
Water  Ice        3     3   3       3        3        3        3      3
       Poison     3     3   3       3        3        3        3      3
       Psychic    5     5   5       5        5        5        5      5
       Rock       4     4   4       4        4        4        4      4
       Steel      1     1   1       1        1        1        1      1

                 Total  Generation
Type 1 Type 2
Bug    Electric      2           2
       Fighting      2           2
       Fire          2           2
       Flying       14          14
       Ghost         1           1
...                ...         ...
Water  Ice           3           3
       Poison        3           3
       Psychic       5           5
       Rock          4           4
       Steel         1           1

[136 rows x 10 columns]